In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
#handle datatypes

df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [6]:
df2 = df.copy()

df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [7]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [9]:
date_str = pd.Series(["2026-12-31"])
type(date_str.dtypes)

pandas.StringDtype

In [10]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [11]:
#handle strings

df["gender"].str.upper()

0        MALE
1        MALE
2      FEMALE
3     UNKNOWN
4      FEMALE
5        MALE
6      FEMALE
7        MALE
8      FEMALE
9        MALE
10        NaN
Name: gender, dtype: str

In [12]:
df["gender"].str.lower()

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: str

In [13]:
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: str

In [14]:
df["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [17]:
df["country"].str.contains("USA")

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [19]:
df["country"].str.contains("usa")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [18]:
df["country"].str.contains("usa", case=False)

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool