In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sorted_data.csv")

In [3]:
df

   Unnamed: 0  id          name   age country   gender   income
0           4   4  Maria Garcia  34.0   Spain   Female      0.0
1           9   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2           3   3          Alex   0.0     USA  Unknown  47000.0
3           5   5        Li Wei  27.0   China     Male  51000.0
4           0   1      John Doe  29.0     USA     Male  55000.0
5          10  10   Emily Davis  31.0     USA        0  58000.0
6           2   2    Jane Smith   0.0  Canada   Female  62000.0
7           8   8    Rachel Lee  29.0     USA   Female  62000.0
8           7   7    Ahmed Khan  38.0       0     Male  68000.0
9           6   6             0  45.0   India   Female  73000.0

In [5]:
# Grouping and Aggregation of Data

df.groupby("country")["income"].mean()

country
0         68000.0
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         0.0
USA       55500.0
Name: income, dtype: float64

In [6]:
df.groupby("country")["income"].min()

country
0         68000.0
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         0.0
USA       47000.0
Name: income, dtype: float64

In [7]:
df.groupby("gender")["income"].mean()

gender
0          58000.0
Female     49250.0
Male       54750.0
Unknown    47000.0
Name: income, dtype: float64

In [8]:
df.groupby("gender")["income"].max()

gender
0          58000.0
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [10]:
df.groupby("country")["income"].agg(["mean", "min", "max"])

            mean      min      max
country
0        68000.0  68000.0  68000.0
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        0.0      0.0      0.0
USA      55500.0  47000.0  62000.0

In [12]:
df.groupby("country")["income"].aggregate(["mean", "min", "max"]) #alias of agg()

            mean      min      max
country
0        68000.0  68000.0  68000.0
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        0.0      0.0      0.0
USA      55500.0  47000.0  62000.0

In [13]:
df.groupby("country")["income"].agg(avg_salary="mean", min_salary="min", max_salary="max")

         avg_salary  min_salary  max_salary
country
0           68000.0     68000.0     68000.0
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           0.0         0.0         0.0
USA         55500.0     47000.0     62000.0

In [14]:
df.groupby("country").agg({
    "income" : "mean",
    "age" : "mean"
})

          income    age
country
0        68000.0  38.00
Canada   62000.0   0.00
China    51000.0  27.00
India    73000.0  45.00
Mexico   45000.0   0.00
Spain        0.0  34.00
USA      55500.0  22.25

In [15]:
df.groupby("country").agg(
    max_salary=("income", "max"),
    avg_age=("age", "mean")
)

         max_salary  avg_age
country
0           68000.0    38.00
Canada      62000.0     0.00
China       51000.0    27.00
India       73000.0    45.00
Mexico      45000.0     0.00
Spain           0.0    34.00
USA         62000.0    22.25