In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df2 = df.copy()

In [5]:
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income"]

In [6]:
df2

    Id          Name   Age Country   Gender   Income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [7]:
df2.rename(columns={"Income": "Salary"})

    Id          Name   Age Country   Gender   Salary
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [8]:
df2.rename(index={1:"First"})

       Id          Name   Age Country   Gender   Income
0       1      John Doe  29.0     USA     Male  55000.0
First   1      John Doe  29.0     USA     Male  55000.0
2       2    Jane Smith   NaN  Canada   Female  62000.0
3       3          Alex   NaN     USA  Unknown  47000.0
4       4  Maria Garcia  34.0   Spain   Female      NaN
5       5        Li Wei  27.0   China     Male  51000.0
6       6           NaN  45.0   India   Female  73000.0
7       7    Ahmed Khan  38.0     NaN     Male  68000.0
8       8    Rachel Lee  29.0     USA   Female  62000.0
9       9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10     10   Emily Davis  31.0     USA      NaN  58000.0

In [9]:
df2.sort_values("Income")

    Id          Name   Age Country   Gender   Income
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
3    3          Alex   NaN     USA  Unknown  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
1    1      John Doe  29.0     USA     Male  55000.0
0    1      John Doe  29.0     USA     Male  55000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
6    6           NaN  45.0   India   Female  73000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN

In [11]:
sorted_df = df2.sort_values("Income", ascending=False)

In [12]:
sorted_df

    Id          Name   Age Country   Gender   Income
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
5    5        Li Wei  27.0   China     Male  51000.0
3    3          Alex   NaN     USA  Unknown  47000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN

In [13]:
sorted_df.sort_index()

    Id          Name   Age Country   Gender   Income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [14]:
#reset index
sorted_df.reset_index()

    index  Id          Name   Age Country   Gender   Income
0       6   6           NaN  45.0   India   Female  73000.0
1       7   7    Ahmed Khan  38.0     NaN     Male  68000.0
2       8   8    Rachel Lee  29.0     USA   Female  62000.0
3       2   2    Jane Smith   NaN  Canada   Female  62000.0
4      10  10   Emily Davis  31.0     USA      NaN  58000.0
5       0   1      John Doe  29.0     USA     Male  55000.0
6       1   1      John Doe  29.0     USA     Male  55000.0
7       5   5        Li Wei  27.0   China     Male  51000.0
8       3   3          Alex   NaN     USA  Unknown  47000.0
9       9   9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10      4   4  Maria Garcia  34.0   Spain   Female      NaN

In [15]:
#drop original index too
sorted_df.reset_index(drop=True)

    Id          Name   Age Country   Gender   Income
0    6           NaN  45.0   India   Female  73000.0
1    7    Ahmed Khan  38.0     NaN     Male  68000.0
2    8    Rachel Lee  29.0     USA   Female  62000.0
3    2    Jane Smith   NaN  Canada   Female  62000.0
4   10   Emily Davis  31.0     USA      NaN  58000.0
5    1      John Doe  29.0     USA     Male  55000.0
6    1      John Doe  29.0     USA     Male  55000.0
7    5        Li Wei  27.0   China     Male  51000.0
8    3          Alex   NaN     USA  Unknown  47000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10   4  Maria Garcia  34.0   Spain   Female      NaN

In [16]:
sorted_df["Ranking"] = sorted_df["Income"].rank()

In [17]:
sorted_df

    Id          Name   Age Country   Gender   Income  Ranking
6    6           NaN  45.0   India   Female  73000.0     10.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0      9.0
8    8    Rachel Lee  29.0     USA   Female  62000.0      7.5
2    2    Jane Smith   NaN  Canada   Female  62000.0      7.5
10  10   Emily Davis  31.0     USA      NaN  58000.0      6.0
0    1      John Doe  29.0     USA     Male  55000.0      4.5
1    1      John Doe  29.0     USA     Male  55000.0      4.5
5    5        Li Wei  27.0   China     Male  51000.0      3.0
3    3          Alex   NaN     USA  Unknown  47000.0      2.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0      1.0
4    4  Maria Garcia  34.0   Spain   Female      NaN      NaN

In [18]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False)

In [19]:
sorted_df

    Id          Name   Age Country   Gender   Income  Ranking
6    6           NaN  45.0   India   Female  73000.0      1.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0      2.0
8    8    Rachel Lee  29.0     USA   Female  62000.0      3.5
2    2    Jane Smith   NaN  Canada   Female  62000.0      3.5
10  10   Emily Davis  31.0     USA      NaN  58000.0      5.0
0    1      John Doe  29.0     USA     Male  55000.0      6.5
1    1      John Doe  29.0     USA     Male  55000.0      6.5
5    5        Li Wei  27.0   China     Male  51000.0      8.0
3    3          Alex   NaN     USA  Unknown  47000.0      9.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0     10.0
4    4  Maria Garcia  34.0   Spain   Female      NaN      NaN

In [21]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="dense")

In [22]:
sorted_df

    Id          Name   Age Country   Gender   Income  Ranking
6    6           NaN  45.0   India   Female  73000.0      1.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0      2.0
8    8    Rachel Lee  29.0     USA   Female  62000.0      3.0
2    2    Jane Smith   NaN  Canada   Female  62000.0      3.0
10  10   Emily Davis  31.0     USA      NaN  58000.0      4.0
0    1      John Doe  29.0     USA     Male  55000.0      5.0
1    1      John Doe  29.0     USA     Male  55000.0      5.0
5    5        Li Wei  27.0   China     Male  51000.0      6.0
3    3          Alex   NaN     USA  Unknown  47000.0      7.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0      8.0
4    4  Maria Garcia  34.0   Spain   Female      NaN      NaN

In [23]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="min")

In [24]:
sorted_df

    Id          Name   Age Country   Gender   Income  Ranking
6    6           NaN  45.0   India   Female  73000.0      1.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0      2.0
8    8    Rachel Lee  29.0     USA   Female  62000.0      3.0
2    2    Jane Smith   NaN  Canada   Female  62000.0      3.0
10  10   Emily Davis  31.0     USA      NaN  58000.0      5.0
0    1      John Doe  29.0     USA     Male  55000.0      6.0
1    1      John Doe  29.0     USA     Male  55000.0      6.0
5    5        Li Wei  27.0   China     Male  51000.0      8.0
3    3          Alex   NaN     USA  Unknown  47000.0      9.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0     10.0
4    4  Maria Garcia  34.0   Spain   Female      NaN      NaN

In [25]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="max")

In [26]:
sorted_df

    Id          Name   Age Country   Gender   Income  Ranking
6    6           NaN  45.0   India   Female  73000.0      1.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0      2.0
8    8    Rachel Lee  29.0     USA   Female  62000.0      4.0
2    2    Jane Smith   NaN  Canada   Female  62000.0      4.0
10  10   Emily Davis  31.0     USA      NaN  58000.0      5.0
0    1      John Doe  29.0     USA     Male  55000.0      7.0
1    1      John Doe  29.0     USA     Male  55000.0      7.0
5    5        Li Wei  27.0   China     Male  51000.0      8.0
3    3          Alex   NaN     USA  Unknown  47000.0      9.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0     10.0
4    4  Maria Garcia  34.0   Spain   Female      NaN      NaN

In [27]:
sorted_df[["Id", "Age", "Country", "Gender", "Income",  "Name"]]

    Id   Age Country   Gender   Income          Name
6    6  45.0   India   Female  73000.0           NaN
7    7  38.0     NaN     Male  68000.0    Ahmed Khan
8    8  29.0     USA   Female  62000.0    Rachel Lee
2    2   NaN  Canada   Female  62000.0    Jane Smith
10  10  31.0     USA      NaN  58000.0   Emily Davis
0    1  29.0     USA     Male  55000.0      John Doe
1    1  29.0     USA     Male  55000.0      John Doe
5    5  27.0   China     Male  51000.0        Li Wei
3    3   NaN     USA  Unknown  47000.0          Alex
9    9   NaN  Mexico     Male  45000.0   Carlos Ruiz
4    4  34.0   Spain   Female      NaN  Maria Garcia