In [1]:
import pandas as pd

In [5]:
# Melt & Pivot

df = pd.DataFrame({
    "country" : ["USA", "USA", "India", "India"],
    "year" : [2024, 2025, 2024, 2025],
    "sales" : [100, 120, 90, 110],
    "profit" : [20, 25, 18, 22],
    "tax" : [10, 20, 30, 40]
})

In [6]:
df

  country  year  sales  profit  tax
0     USA  2024    100      20   10
1     USA  2025    120      25   20
2   India  2024     90      18   30
3   India  2025    110      22   40

In [9]:
# Melt

melted_df = df.melt(
    id_vars=["country", "year"], #keep
    value_vars=["sales", "profit", "tax"], #unpivot
    var_name="metrics",
    value_name="value"
)

In [10]:
melted_df

   country  year metrics  value
0      USA  2024   sales    100
1      USA  2025   sales    120
2    India  2024   sales     90
3    India  2025   sales    110
4      USA  2024  profit     20
5      USA  2025  profit     25
6    India  2024  profit     18
7    India  2025  profit     22
8      USA  2024     tax     10
9      USA  2025     tax     20
10   India  2024     tax     30
11   India  2025     tax     40

In [11]:
# Pivot

pivoted_df = melted_df.pivot(
    index=["country", "year"],
    columns="metrics",
    values="value"
)

In [12]:
pivoted_df

metrics       profit  sales  tax
country year
India   2024      18     90   30
        2025      22    110   40
USA     2024      20    100   10
        2025      25    120   20