In [1]:
import pandas as pd

In [2]:
# Merging & Joining Data

df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Aven", "Bella", "Chloe", "Daisy"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [3]:
df_customers

   customer_id   name
0            1   Aven
1            2  Bella
2            3  Chloe
3            4  Daisy

In [4]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [6]:
pd.merge(df_customers, df_orders, on="customer_id") # inner join

   customer_id   name  order_id  amount
0            1   Aven       102     120
1            2  Bella       101     250
2            4  Daisy       103     300

In [7]:
pd.merge(df_customers, df_orders, on="customer_id", how="left") # left join

   customer_id   name  order_id  amount
0            1   Aven     102.0   120.0
1            2  Bella     101.0   250.0
2            3  Chloe       NaN     NaN
3            4  Daisy     103.0   300.0

In [8]:
pd.merge(df_customers, df_orders, on="customer_id", how="right") # right join

   customer_id   name  order_id  amount
0            2  Bella       101     250
1            1   Aven       102     120
2            4  Daisy       103     300
3            5    NaN       104     180

In [9]:
pd.merge(df_customers, df_orders, on="customer_id", how="outer") # outer join

   customer_id   name  order_id  amount
0            1   Aven     102.0   120.0
1            2  Bella     101.0   250.0
2            3  Chloe       NaN     NaN
3            4  Daisy     103.0   300.0
4            5    NaN     104.0   180.0